name: fullstackoauth
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  internet_connection_checker: ^1.0.0+1
  go_router: ^14.2.3
  flutter_bloc: ^8.1.6
  get_it: ^7.7.0
  equatable: ^2.0.5
  dartz: ^0.10.1
  shared_preferences: ^2.3.1
  sqflite: ^2.3.3+1
  http: ^1.2.2
  intl: ^0.19.0
  flutter_localization: ^0.2.1
  flutter_intl: ^0.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  intl_utils: ^2.8.7

flutter:
  uses-material-design: true
  generate: true

flutter_intl:
  enabled: true
  class_name: S
  main_locale: en
  arb_dir: lib/core/l10n
  output_dir: lib/core/l10n/generated