name: fullstackoauth
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_riverpod: ^2.5.1
  sqflite: ^2.3.3+1
  shared_preferences: ^2.3.1
  internet_connection_checker: ^1.0.0+1
  dartz: ^0.10.1
  equatable: ^2.0.5
  get_it: ^7.7.0
  flutter_bloc: ^8.1.6
  go_router: ^14.2.3

flutter:
  uses-material-design: true
